name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "python3.10"

jobs:
  build-artifacts:
    
    strategy:
      matrix:
        include:
          - arch: grayskull
            env_script: env_for_silicon.sh
          - arch: wormhole_b0
            env_script: env_for_wormhole_b0.sh
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
        with:
          os: ubuntu-22.04
      - name: Update submodule
        run: git submodule update --init --recursive
      - name: Build for ${{ matrix.arch }}
        run: source ${{ matrix.env_script }}
